common: &common
  steps:
    - checkout
    - restore_cache:
        key: "{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum \".circleci/config.yml\" }}-{{ checksum \"package-lock.json\" }}"
    - run: node --version
    - run: npm --version
    - run: npm ci
    - run: npm test
    - save_cache:
        key: "{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum \".circleci/config.yml\" }}-{{ checksum \"package-lock.json\" }}"
        paths:
          - /home/circleci/.npm

version: 2
jobs:
  node-8:
    docker:
      - image: circleci/node:8-stretch
    <<: *common

  node-10:
    docker:
      - image: circleci/node:10-stretch
    <<: *common

workflows:
  version: 2
  test:
    jobs:
      - node-8
      - node-10
